[package]
name = "zscm-article"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"]}
axum = { version = "0.7.4" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
clap = { version = "*", features = [ "derive" ] }
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
] } # 处理 HTTP 请求和流式响应
anyhow = "*"
toml = "*"
md5 = "*"
chrono = "*"
base64 = "*"
percent-encoding = "*"
regex = { version = "1.10", default-features = false, features = ["std", "unicode"] }
scraper = "0.18"

[dev-dependencies]
sqlx = { version = "0.6", features = [
    "runtime-tokio-native-tls",
    "sqlite",
    "json",
] }
